name: 'coTester.ai - trigger tests in github'
description: 'Trigger coTester.ai tests in github actions'
author: 'coTester.ai'
inputs:
  url:
    description: 'Url of the cotester.ai instance. Needs for debug'
    required: false
  token:
    description: 'Token to authenticate with coTester.ai'
    required: true
  project:
    description: 'Project name in cotester.ai'
    required: true
  include:
    description:
      'Set of include tags separated by comma to trigger tests. Default all'
    required: false
  exclude:
    description:
      'Set of exclude tags separated by comma to trigger tests. Default none'
    required: false
  github-token:
    description: 'Github token to authenticate with github'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
