name: 'coTester.ai - trigger tests in github'
description: 'Trigger coTester.ai tests in github actions'
author: 'coTester.ai'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  url:
    description: 'Url of the cotester.ai instance. Needs for debug'
    required: false
  secretKey:
    description: 'API Key to authenticate with coTester.ai'
    required: true
  project:
    description: 'Project name in cotester.ai'
    required: true
  group:
    description: 'Group name in cotester.ai. Default all'
    required: false
  max_parallel_runs:
    description: 'Maximum amount of parallel tests runs'
    required: false
  proxy_url:
    description: 'Proxy url to use for the tests'
    required: false
  proxy_username:
    description: 'Proxy username to use for the tests'
    required: false
  proxy_password:
    description: 'Proxy password to use for the tests'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
